---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---


## Load libraries

```{r}
library(plotrix)
library(suncalc)
library(lunar)
library(ggplot2)
library(tidyverse)
library(gridExtra)
library(circular)
library(pscl)
library(maptools)
library(rgdal)
library(rgeos)
library(glmmTMB)
library(emmeans)
library(doBy)
library(MASS)
library(plyr)
library(ggspatial)
#library(rasterVis)
library(ggsn)
library(grid)
library(itsadug)
library(car)

```

## Functions needed

```{r}
 
LIC<-function(x,crit="AIC"){
    if(crit=="AIC"){IC<-function(x,...)AIC(x,...)}
    if(crit=="BIC"){IC<-function(x,...)BIC(x,...)}
    out<-NULL
    for(i in 1:length(x)){
      ic<-try(IC(x[[i]]))
      this<-NA
      if(!'try-error'%in%class(ic))this<-ic
      out<-c(out,this)
    }
    return(out)
  }
  
  #CALC EQUIVALENT DF FOR A GAM, GLM, etc
edf<-function(x){
    isbad<-'try-error'%in%class(try(nobs(x),silent=TRUE))
    if(!isbad)return(nobs(x)-df.residual(x))
    if(isbad)return(NA)
  } 

ictab<-function(x){
    modz<-names(x)
    aicz<-LIC(x,crit="AIC")
    bicz<-LIC(x,crit="BIC")
    dfz<-unlist(lapply(x,FUN=edf))
    dfz<-round(unlist(lapply(x,FUN=edf)),3)
    daicz<-round(aicz-min(aicz,na.rm=TRUE),1)
    dbicz<-round(bicz-min(bicz,na.rm=TRUE),1)
    wa<-aicz; wa[is.na(wa)]<-Inf;  # wa<-round(Weights(wa),3) # Weights(wa) was erroring
    wb<-bicz; wb[is.na(wb)]<-Inf;  # wb<-round(Weights(wb),3) # Weights(wb) was erroring
    #de<-round(unlist(lapply(x,FUN=devexp)),1)
    df<-data.frame(mod=modz,wA=wa,wB=wb,dAIC=daicz,dBIC=dbicz,AIC=aicz,BIC=bicz,edf=dfz)
    rownames(df)<-NULL
    return(df)
  }
  
  predict_multimod<-function(modz,weights=rep(1,length(modz)),newdata=NULL,type='response',se.fit=FALSE){
    out<-NULL
    for(m in modz){
      this<-predict(m,newdata=newdata,type=type,se.fit=se.fit)
      out<-cbind(out,this)
    }
    weights<-weights/sum(weights) #NORMALIZE TO SUM TO 1
    return(rowSums(t(t(out)*weights)))
  }
  
 make_circ<-function(d){
    out<-d
    namez<-names(d)
    if("H"%in%namez){
      out$Hsin<-sin(2*pi*(out$H/24))
      out$Hcos<-cos(2*pi*(out$H/24))
    }
    if("J"%in%namez){
      out$Jsin<-sin(2*pi*(out$J/365))
      out$Jcos<-cos(2*pi*(out$J/365))
    }
    if("MOON"%in%namez){
      out$Msin<-sin(out$MOON)
      out$Mcos<-cos(out$MOON)
      out$MOON2<-out$MOON
      out$MOON2[out$MOON2>pi]<-out$MOON2[out$MOON2>pi]-pi
      out$MOON2<-2*out$MOON2
      out$Lsin<-sin(out$MOON2) #SEMI-LUNAR
      out$Lcos<-cos(out$MOON2) #SEMI-LUNAR
    }
    return(out)
  }


```

## Load data

```{r}
load("data/gsub.rdat")
load("data/pam_mixed_modz.rdat")

```

## Identify top models for model averaging

```{r}
  names(bmodz)<-paste("b",1:length(bmodz),sep="")
  btab<-ictab(bmodz) # only got this to run by commenting out part of the ictab function
  btab$mod<-names(bmodz) 
  btab$form<-unlist(lapply(bmodz,function(x){unfun(x[["modelInfo"]]$allForm$formula)}))
  btab$loglik<-unlist(lapply(bmodz,logLik))
  btab$dup<-duplicated(btab[,-1])
  btab$CAND<-grepl("rW",btab$form)&!is.na(btab$AIC)&!btab$dup #A CANDIDATE MODEL FORM?
  btab$dAIC[btab$CAND]<-btab$AIC[btab$CAND]-min(btab$AIC[btab$CAND],na.rm=TRUE)
  btab$w<-round(exp(-0.5*btab$dAIC)/sum(exp(-0.5*btab$dAIC),na.rm=TRUE),4)
  btab$PRED<-btab$w>0.1&!is.na(btab$w)
  btab<-btab[order(-btab$CAND,btab$AIC),][c("mod","form","loglik","AIC","dAIC","w","edf","PRED")]
  btab
  write.csv(btab,file="data/bmod_aic.csv")
  
  #zmodz<-list(z_0,z_w,z_w1,z_w2,z_w3,z_w_z1,z_w_z2,z_w_z3,z_w_z4,z_w_z5,z_w_z6,z_w_z9,z_w_z10,z_w_z11,z_w_z12,z_w_z13,z_w_z14)
  #names(zmodz)<-lapply(zmodz,FUN=function(x){unfun(formula(x))})
  #zmodz[[length(zmodz)+1]]<-zxx5
  names(zmodz)<-paste("z",1:length(zmodz),sep="")
  ztab<-ictab(zmodz)
  ztab$mod<-names(zmodz)
  ztab$form<-unlist(lapply(zmodz,function(x){unfun(x[["modelInfo"]]$allForm$formula)}))
  ztab$ziform<-unlist(lapply(zmodz,function(x){unfun(x[["modelInfo"]]$allForm$ziformula)}))
  ztab$loglik<-unlist(lapply(zmodz,logLik))
  ztab$dup<-duplicated(ztab[,-1])
  ztab$CAND<-grepl("rW",ztab$form)&!grepl("DEPTH",ztab$form)&!is.na(ztab$AIC)&!ztab$dup
  ztab$dAIC[ztab$CAND]<-ztab$AIC[ztab$CAND]-min(ztab$AIC[ztab$CAND],na.rm=TRUE)
  ztab$w<-round(exp(-0.5*ztab$dAIC)/sum(exp(-0.5*ztab$dAIC),na.rm=TRUE),4)
  ztab$PRED<-ztab$w>0.1&!is.na(ztab$w)
  ztab<-ztab[order(-ztab$CAND,ztab$AIC),][c("mod","form","ziform","loglik","AIC","dAIC","w","edf","PRED")]
  ztab
  write.csv(ztab,file="data/zmod_aic.csv")

bbest_mm<-bmodz[btab$mod[btab$PRED]]
zbest_mm<-zmodz[ztab$mod[ztab$PRED]]
bbest_wts<-btab$w[match(names(bbest_mm),btab$mod)]
zbest_wts<-ztab$w[match(names(zbest_mm),ztab$mod)]

```

## Summarize estimated marginal means

```{r}
  #DIEL FX
  print("Diel FX")
  nd<-expand.grid(Y=as.character(unique(gsub$Y)),Site=as.character(unique(gsub$Site)),J=335,MOON=pi,H=0:24,WK=NA,DAY=NA,DEPTH=50)
  nd<-make_circ(nd)
  #nd$pG<-predict(bbest,newdata=nd,type='response')
  #nd$rG<-predict(zbest,newdata=nd,type='response')
  #nd$pG<-predict_multimod(bbest_mm,weights=bbest_wts,newdata=nd,type='response')
  nd<-cbind(nd,
  test = predict_multimod(bbest_mm,weights=bbest_wts,newdata=nd,type='response', se.fit = TRUE))
  nd$rG<-predict_multimod(zbest_mm,weights=zbest_wts,newdata=nd,type='response')
  emm_h<-summaryBy(cbind(pG,rG)~H,data=nd,FUN=mean,keep.names=TRUE)
  
  #LUNAR FX
  print("Lunar FX")
  nd<-expand.grid(Y=as.character(unique(gsub$Y)),Site=as.character(unique(gsub$Site)),J=335,MOON=seq(0,2*pi,length=16),H=0,WK=NA,DAY=NA,DEPTH=50)
  nd<-make_circ(nd)
  #nd$pG<-predict(bbest,newdata=nd,type='response')
  #nd$rG<-predict(zbest,newdata=nd,type='response')
  nd$pG<-predict_multimod(bbest_mm,weights=bbest_wts,newdata=nd,type='response')
  nd$rG<-predict_multimod(zbest_mm,weights=zbest_wts,newdata=nd,type='response')
  emm_l<-summaryBy(cbind(pG,rG)~MOON,data=nd,FUN=mean,keep.names=TRUE) 
  
  #SEASONAL FX - OVERALL
  print("Seasonal FX")
  nd<-expand.grid(Y=as.character(unique(gsub$Y)),Site=as.character(unique(gsub$Site)),J=275:400,MOON=pi,H=0,WK=NA,DAY=NA,DEPTH=50)
  nd<-make_circ(nd)
  #nd$pG<-predict(bbest,newdata=nd,type='response')
  #nd$rG<-predict(zbest,newdata=nd,type='response')
  nd$pG<-predict_multimod(bbest_mm,weights=bbest_wts,newdata=nd,type='response')
  nd$rG<-predict_multimod(zbest_mm,weights=zbest_wts,newdata=nd,type='response')
  emm_j<-summaryBy(cbind(pG,rG)~J,data=nd,FUN=mean,keep.names=TRUE)
  emm_j$edate<-as.Date('2010-12-31')+emm_j$J
  
  #SEASONAL x SITE FX
  print("Seasonal X Site FX")
  nd<-expand.grid(Y=as.character(unique(gsub$Y)),Site=as.character(unique(gsub$Site)),J=282:365,MOON=pi,H=0,WK=NA,DAY=NA,DEPTH=50)
  nd<-make_circ(nd)
  #nd$pG<-predict(bbest,newdata=nd,type='response')
  #nd$rG<-predict(zbest,newdata=nd,type='response')
  nd$pG<-predict_multimod(bbest_mm,weights=bbest_wts,newdata=nd,type='response')
  nd$rG<-predict_multimod(zbest_mm,weights=zbest_wts,newdata=nd,type='response')
  emm_js<-summaryBy(cbind(pG,rG)~J+Site,data=nd,FUN=mean,keep.names=TRUE)
  emm_js$edate<-as.Date('2010-12-31')+emm_js$J
  sitz<-unique(emm_js$Site)
  peakz<-NULL
  for(s in 1:length(sitz)){
    sub<-subset(emm_js,Site==sitz[s])
    pk_pG<-sub$edate[sub$pG==max(sub$pG)]
    pk_rG<-sub$edate[sub$rG==max(sub$rG)]
    df<-data.frame(Site=sitz[s],peak_pG=pk_pG,peak_rg=pk_rG)
    peakz<-rbind(peakz,df)
  }
  
  #SITE FX
  print("Site FX")
  nd<-expand.grid(Y=as.character(unique(gsub$Y)),Site=as.character(unique(gsub$Site)),J=282:365,MOON=pi,H=0,WK=NA,DAY=NA,DEPTH=50)
  nd<-make_circ(nd)
  #nd$pG<-predict(bbest,newdata=nd,type='response')
  #nd$rG<-predict(zbest,newdata=nd,type='response')
  nd$pG<-predict_multimod(bbest_mm,weights=bbest_wts,newdata=nd,type='response')
  nd$rG<-predict_multimod(zbest_mm,weights=zbest_wts,newdata=nd,type='response')
  emm_s<-summaryBy(cbind(pG,rG)~Site,data=nd,FUN=mean,keep.names=TRUE)
  
  #ANNUAL
  print("Annual FX")
  nd<-expand.grid(Y=as.character(unique(gsub$Y)),Site=as.character(unique(gsub$Site)),J=282:365,MOON=pi,H=0,WK=NA,DAY=NA,DEPTH=50)
  nd<-make_circ(nd)
  #nd$pG<-predict(bbest,newdata=nd,type='response')
  #nd$rG<-predict(zbest,newdata=nd,type='response')
  nd$pG<-predict_multimod(bbest_mm,weights=bbest_wts,newdata=nd,type='response')
  nd$rG<-predict_multimod(zbest_mm,weights=zbest_wts,newdata=nd,type='response')
  emm_y<-summaryBy(cbind(pG,rG)~Y,data=nd,FUN=mean,keep.names=TRUE)
  #emm_y<-summaryBy(pG~Y,data=nd,FUN=mean,keep.names=TRUE)
  emm_y$Y<-as.numeric(as.character(emm_y$Y))
  emm_y<-emm_y[order(emm_y$Y),]
  plot(pG~Y,data=emm_y,type='l')
  
  #emm_ys<-summaryBy(cbind(pG,rG)~Y+Site,data=nd,FUN=mean,keep.names=TRUE)
  emm_ys<-summaryBy(pG~Y+Site,data=nd,FUN=mean,keep.names=TRUE)
  emm_ys$Y<-as.numeric(as.character(emm_ys$Y))
  emm_ys<-emm_ys[order(emm_ys$Y),]
  
  sitz<-unique(emm_ys$Site)
  emm_ys$SiteY<-paste(emm_ys$Site,emm_ys$Y,sep="_")
  plot(pG~Y,data=emm_ys,col=Site,type='n')
  for(s in 1:length(sitz)){
    ltx<-ceiling(s/8)
    lines(pG~Y,data=emm_ys,subset=Site==sitz[s],col=alpha(s,0.33),lty=ltx)
    esub<-subset(emm_ys,SiteY%in%gsub$SiteY)
    lines(pG~Y,data=esub,subset=Site==sitz[s],col=s,lwd=2,lty=ltx)
  }
  legend("topleft",legend=sitz,col=1:length(sitz),cex=0.85,lty=ceiling((1:length(sitz))/8),lwd=2)
  
}

#GGPLOT FIGURE of DIEL, LUNAR FX
if(TRUE){
  alf<-0.5
  yfrac<-0.95
  ############

  ###########
  #PRESENCE
  ymn<-min(c(emm_h$pG,emm_l$pG))
  ymx<-max(c(emm_h$pG,emm_l$pG))
  yrange<-ymx-ymn
  ymn<-ymn-(yrange*0.25)
  ymx<-ymx+(yrange*0.25)

  #DIEL PRESENCE
  xmx<-24
  labz_h<-data.frame(H=c(23,5.5,11,16.5),lab=c("Night","","Day",""))
  colz_h<-rep("black",24); colz_h[7:16]<-"white"; colz_h[c(6,17)]<-"darkgray"; 
  pg_circ_h<-ggplot()+
      geom_rect(aes(xmin=0:23,xmax=1:24,ymin=!!ymn,ymax=!!ymx*yfrac),fill=alpha(colz_h,alf))+
      coord_polar()+geom_line(data=emm_h,aes(x=H,y=pG),lwd=2)+
      ylim(ymn,ymx)+theme_minimal()+
      theme(
        axis.title = element_blank(),
        axis.text.x = element_blank(),
        plot.title = element_text(hjust=0.5,vjust=1)
      ) +
      ggtitle("Grunt Presence")+
      geom_text(data=labz_h, aes(x=H, y=!!ymx, label=lab, hjust=0.5), color="black", size=4 ) 
    
  
  #LUNAR PRESENCE
  seq_l<-seq(0,2*pi,length=32)
  crp_l<-colorRampPalette(c("black","white","black"))
  colz_l<-crp_l(length(seq_l)-1)
  labz_l<-data.frame(MOON=c(0,pi/2,pi,pi*1.5),lab=c("New Moon","","Full Moon",""))
  pg_circ_l<-ggplot()+geom_rect(aes(xmin=seq_l[-length(seq_l)],xmax=seq_l[-1],ymin=!!ymn,ymax=!!ymx*yfrac),fill=alpha(colz_l,alf))+
    coord_polar()+geom_line(data=emm_l,aes(x=MOON,y=pG),lwd=2)+ylim(ymn,ymx)+
    theme_minimal()+
    theme(
      axis.title = element_blank(),
      axis.text.x = element_blank(),
      plot.title = element_text(hjust=0.5,vjust=1)
    ) +
    xlab("Lunar")+
    geom_text(data=labz_l, aes(x=MOON, y=!!ymx, label=lab, hjust=0.5), color="black", size=4 ) 
  
  
  ############
  #RATE
  ymn<-min(c(emm_h$rG,emm_l$rG))
  ymx<-max(c(emm_h$rG,emm_l$rG))
  yrange<-ymx-ymn
  ymn<-ymn-(yrange*0.25)
  ymx<-ymx+(yrange*0.25)
  
  #DIEL RATE
  labz_h<-data.frame(H=c(23,5.5,11,16.5),lab=c("Night","","Day",""))
  colz_h<-rep("black",24); colz_h[7:16]<-"white"; colz_h[c(6,17)]<-"darkgray"; 
  rg_circ_h<-ggplot()+
    geom_rect(aes(xmin=0:23,xmax=1:24,ymin=!!ymn,ymax=!!ymx*yfrac),fill=alpha(colz_h,alf))+
    coord_polar()+geom_line(data=emm_h,aes(H,rG),lwd=2)+ylim(ymn,ymx)+theme_minimal()+
    theme(
      axis.title.y=element_blank(),
      axis.title.x=element_blank(),
      axis.text.x = element_blank(),
      plot.title = element_text(hjust=0.5,vjust=1)
    ) +
    ggtitle("Grunt Rate")+
    geom_text(data=labz_h, aes(x=H, y=!!ymx, label=lab, hjust=0.5), color="black", size=4 ) 
  
  #LUNAR RATE
  seq_l<-seq(0,2*pi,length=32)
  crp_l<-colorRampPalette(c("black","white","black"))
  colz_l<-crp_l(length(seq_l)-1)
  labz_l<-data.frame(MOON=c(0,pi/2,pi,pi*1.5),lab=c("New Moon","","Full Moon",""))
  rg_circ_l<-ggplot()+geom_rect(aes(xmin=seq_l[-length(seq_l)],xmax=seq_l[-1],ymin=!!ymn,ymax=!!ymx*yfrac),fill=alpha(colz_l,alf))+
    coord_polar()+geom_line(data=emm_l,aes(x=MOON,y=rG),lwd=2)+ylim(ymn,ymx)+
    theme_minimal()+
    theme(
      axis.title = element_blank(),
      axis.text.x = element_blank(),
      plot.title = element_text(hjust=0.5,vjust=1)
    ) +
    geom_text(data=labz_l, aes(x=MOON, y=!!ymx, label=lab, hjust=0.5), color="black", size=4 ) 
  
  grid.arrange(pg_circ_h,rg_circ_h,pg_circ_l,rg_circ_l,nrow=2)
  
  ht<-5 #HEIGHT OF PLOT IN INCHES
  nr<-2; nc<-2; lmat<-matrix(seq_len(nr*nc),nrow=nr,ncol=nc,byrow=TRUE)
  #ggsave("diel_lunar_fx.jpg",marrangeGrob(list(pg_circ_h,rg_circ_h,pg_circ_l,rg_circ_l),layout_matrix=lmat,top="",padding=unit(0,"line")),width=ht*1,height=ht,dpi=600)
  ggsave("diel_lunar_fx.pdf",marrangeGrob(list(pg_circ_h,rg_circ_h,pg_circ_l,rg_circ_l),layout_matrix=lmat,top="",padding=unit(0,"line")),width=ht*1,height=ht,dpi=600)
  
}






```

